ingressClass:
  enabled: true
  isDefaultClass: true

providers:
  kubernetesIngress:
    enabled: true
  kubernetesCRD:
    enabled: true
  kubernetesGateway:
    enabled: false

gateway:
  enabled: false

gatewayClass:
  enabled: false

service:
  spec:
    type: ClusterIP

ports:
  web:
    hostPort: 80
  websecure:
    hostPort: 443

nodeSelector:
  ingress-node: "true"


deployment:
  strategy:
    type: Recreate
